from typing import Any, List
from olexFunctions import OlexFunctions

# --- Constants ---
black: str
white: str
table_col: str

# --- Instances ---
OV: OlexFunctions

# --- Classes ---
class ImageListener_:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

ImageListener: ImageListener_

# --- Functions ---
def About() -> None: ...
def FileOpen(args: Any = ...) -> str: ...
def FileSave(args: Any = ...) -> str: ...
def FixFree(args: Any = ...) -> None: ...
def GetBoxPosition(args: Any = ...) -> Any: ...
def GetDropdownItemsFromList(lst: List[str]) -> str: ...
def GetFileList(path: str = ...) -> List[str]: ...
def GetFileListAsDropdownItems(path: str = ...) -> str: ...
def GetFolderList(path: str = ...) -> List[str]: ...
def GetItemsFromPhilChoices(args: Any = ...) -> List[str]: ...
def GetPathParam(name: str) -> str: ...
def IsMouseLocked() -> bool: ...
def NamingMode(args: Any = ...) -> Any: ...
def PopTool(args: Any = ...) -> None: ...
def SaveModel(args: Any = ...) -> None: ...
def SwitchPanel(panel: str) -> None: ...
def SwitchSettings(args: Any = ...) -> None: ...
def SwitchTool(tool: str) -> None: ...
def UpdateWeight(args: Any = ...) -> None: ...
def activate_or_run_CAP(args: Any = ...) -> None: ...
def run_CAP(args: Any = ...) -> None: ...
def cbtn_on(args: Any = ...) -> None: ...
def copy_datadir_items(args: Any = ...) -> None: ...
def copytree(src: str, dst: str) -> None: ...
def create_archive(args: Any = ...) -> None: ...
def create_history_branch(args: Any = ...) -> None: ...
def create_overlay_gui(args: Any = ...) -> None: ...
def delete_ofile(args: Any = ...) -> None: ...
def do_sort(args: Any = ...) -> None: ...
def escape_for_html(s: str) -> str: ...
def file_open(path: str) -> None: ...
def focus_on_control(control: str) -> None: ...
def get_default_notification() -> Any: ...
def get_notification(args: Any = ...) -> Any: ...
def get_openblas_thread_n_selection() -> Any: ...
def get_refinement_lists() -> List[str]: ...
def get_thread_n_label() -> str: ...
def get_thread_n_selection() -> Any: ...
def have_par_files() -> bool: ...
def helpImagesToOlexVFS() -> None: ...
def par_files_table(args: Any = ...) -> str: ...
def set_client_mode(args: Any = ...) -> None: ...
def set_notification(args: Any = ...) -> None: ...
def set_ofile(args: Any = ...) -> None: ...
def set_openblas_thread_n(args: Any = ...) -> None: ...
def set_refinement_list(args: Any = ...) -> None: ...
def strip_html_tags(s: str) -> str: ...
def zipToOlexVFS(args: Any = ...) -> None: ...
