from typing import Any, List, Optional
from olexFunctions import OlexFunctions
from datetime import date

# --- Instances ---
OV: OlexFunctions

# --- Constants / state ---
HaveModeBox: bool
debug: bool
hover_buttons: bool
tutorial_box_initialised: bool
current_tooltip_number: int
time_add: int
last_mode: Optional[str]
last_mode_options: Optional[str]

# --- Functions ---
def CheckForImage(args: Any = ...) -> Any: ...
def EditGuiItem(args: Any = ...) -> None: ...
def InActionButton(args: Any = ...) -> bool: ...
def MakeActiveGuiButton(args: Any = ...) -> str: ...
def MakeHoverButton(args: Any = ...) -> str: ...
def MakeHoverButtonOff(args: Any = ...) -> str: ...
def MakeHoverButtonOn(args: Any = ...) -> str: ...
def OnModeChange(args: Any = ...) -> None: ...
def OnStateChange(args: Any = ...) -> None: ...
def PopBanner(args: Any = ...) -> None: ...
def PopProgram(args: Any = ...) -> None: ...
def SetReportStyle(style: str) -> None: ...
def SetReportTemplate(template: str) -> None: ...
def _check_modes_and_states(args: Any = ...) -> Any: ...
def bgcolor(args: Any = ...) -> str: ...
def changeBoxColour(args: Any = ...) -> None: ...
def doBanner(args: Any = ...) -> None: ...
def format_help(args: Any = ...) -> str: ...
def getGenericSwitchName(args: Any = ...) -> str: ...
def getGenericSwitchNameTranslation(args: Any = ...) -> str: ...
def getPopBoxPosition(args: Any = ...) -> Any: ...
def getPrintStyles() -> List[str]: ...
def getStyles() -> List[str]: ...
def getStylesList() -> List[str]: ...
def getTemplatesList() -> List[str]: ...
def getTip(args: Any = ...) -> str: ...
def get_template(name: str) -> str: ...
def include_block(args: Any = ...) -> str: ...
def makeHtmlBottomPop(args: Any = ...) -> str: ...
def makeHtmlInputBox(args: Any = ...) -> str: ...
def makeHtmlTable(args: Any = ...) -> str: ...
def makeHtmlTableRow(args: Any = ...) -> str: ...
def make_combo_text_box(args: Any = ...) -> str: ...
def make_edit_link(args: Any = ...) -> str: ...
def make_gui_edit_link(args: Any = ...) -> str: ...
def make_help_href(args: Any = ...) -> str: ...
def make_html_closing() -> str: ...
def make_html_opening(args: Any = ...) -> str: ...
def make_input_button(args: Any = ...) -> str: ...
def make_input_text_box(args: Any = ...) -> str: ...
def make_spin_input(args: Any = ...) -> str: ...
def make_table_first_col(args: Any = ...) -> str: ...
def make_tick_box_input(args: Any = ...) -> str: ...
def make_warning_html(message: str) -> str: ...
def path_from_phil(args: Any = ...) -> str: ...
def reg_command(args: Any = ...) -> None: ...
def setDisplayQuality(quality: str) -> None: ...
def switchButton(args: Any = ...) -> None: ...
