def f(expression: str) -> str: ...
def f_ex(expression: str) -> str: ...
def m(command: str) -> None: ...
def post(message: str) -> None: ...
def readImage(path: str) -> object: ...
def writeImage(path: str, image: object) -> None: ...
def getProfileInfo() -> str: ...
def registerFunction(fn: object, profiling: bool, namespace: str) -> None: ...
def registerMacro(fn: object, options: str, profiling: bool) -> None: ...
def registerCallback(event: str, fn: object) -> None: ...
def unregisterCallback(event: str, fn: object) -> None: ...
