from typing import Any, Iterator, List, Dict, Tuple

class OlexRefinementModel:
    # Private attributes (typed for reference)
    _afix: Any
    _atoms: list
    _cell: tuple
    _fixed_variables: list

    def __init__(self) -> None: ...

    # Cell
    def getCell(self) -> tuple: ...
    def getCellErrors(self) -> tuple: ...

    # Atoms
    def atoms(self) -> List[Dict]: ...
    def atom_ids(self) -> List[int]: ...
    def numberAtoms(self) -> int: ...
    def number_non_hydrogen_atoms(self) -> int: ...
    def get_unique_types(self) -> List[str]: ...
    def currentFormula(self) -> str: ...
    def disorder_parts(self) -> List[int]: ...

    # Q peaks
    def getExpectedPeaks(self) -> int: ...
    def getExpectedPeaks_and_AtomsPresent(self) -> Tuple[int, int]: ...

    # Iterators
    def iterator(self) -> Iterator[Dict]: ...
    def afix_iterator(self) -> Iterator[Dict]: ...
    def constraints_iterator(self) -> Iterator[Dict]: ...
    def restraints_iterator(self) -> Iterator[Dict]: ...
    def disp_iterator(self) -> Iterator[Dict]: ...
    def same_iterator(self) -> Iterator[Dict]: ...

    # Constraints / Restraints
    def constraint_types(self) -> List[str]: ...
    def restraint_types(self) -> List[str]: ...
    def adp_constraints(self) -> List[Dict]: ...
    def is_adp_restraint(self, restraint: Any) -> bool: ...

    # Model / experimental
    def model(self) -> Dict: ...
    def exptl(self) -> Dict: ...


# --- Module-level functions ---
def AvailableExternalPrograms() -> List[str]: ...
def AvailableExternalProgramsHtml() -> str: ...
def AvailablePlugins() -> List[str]: ...
def AvailableSkins() -> List[str]: ...
def InstalledPlugins() -> List[str]: ...
def GetCurrentSelection() -> str: ...
def GetHklFileList() -> List[str]: ...
def GetHklFileValue(key: str) -> Any: ...
def GetHttpFile(url: str, path: str = ...) -> None: ...
def GetOptionalHyphenString(s: str) -> str: ...
def GetRcolour(args: Any = ...) -> Any: ...
def GetTwinLawAndBASF() -> Tuple[Any, float]: ...
def FindZOfHeaviestAtomInFormula(formula: str) -> int: ...
def ChooseLabelContent(args: Any = ...) -> Any: ...
def EditIns(args: Any = ...) -> None: ...
def FixMACQuotes(s: str) -> str: ...
def SetAtomicVolumeInSnumPhil(args: Any = ...) -> None: ...
def SetFormulaFromInput(formula: str) -> None: ...
def SetMasking(args: Any = ...) -> None: ...
def StoreSingleParameter(name: str, value: Any) -> None: ...
def StringsAreEqual(a: str, b: str) -> bool: ...
def StringsAreNotEqual(a: str, b: str) -> bool: ...
def SpyVar(name: str) -> Any: ...
def MakeMovie(args: Any = ...) -> None: ...
def ExternalPrgParameters(args: Any = ...) -> Any: ...
def haveSelection() -> bool: ...
def haveGUI() -> bool: ...
def check_for_selection() -> bool: ...
def check_for_recent_update() -> bool: ...
def expand(args: Any = ...) -> Any: ...
def collect(args: Any = ...) -> Any: ...
def dump(obj: Any) -> None: ...
def dump_garbage() -> None: ...
def fade_in(args: Any = ...) -> None: ...
def fade_out(args: Any = ...) -> None: ...
def formatted_date_from_timestamp(ts: float) -> str: ...
def getAllHelpBoxes() -> List[Any]: ...
def getCellHTML() -> str: ...
def getFileContents(path: str) -> str: ...
def getKey(d: dict, key: str) -> Any: ...
def getKeys(d: dict) -> List[str]: ...
def getObjectCount() -> int: ...
def get_all_objects() -> List[Any]: ...
def get_auto_q_peaks() -> Any: ...
def get_refcounts() -> Any: ...
def get_refine_ls_hydrogen_treatment() -> str: ...
def get_refinement_methods() -> List[str]: ...
def get_refinement_programs() -> List[str]: ...
def get_solution_methods() -> List[str]: ...
def get_solution_programs() -> List[str]: ...
def get_text_from_vfs(path: str) -> str: ...
def install_plugin(name: str) -> None: ...
def onRefinementMethodChange(args: Any = ...) -> None: ...
def onRefinementProgramChange(args: Any = ...) -> None: ...
def onSolutionMethodChange(args: Any = ...) -> None: ...
def onSolutionProgramChange(args: Any = ...) -> None: ...
def reset_file_in_OFS(path: str) -> None: ...
def revert_to_original() -> None: ...
def round_to_n_digits(value: float, n: int) -> float: ...
def runSadabs(args: Any = ...) -> None: ...
def setAllMainToolbarTabButtons(args: Any = ...) -> None: ...
def setMainToolbarTabButtons(args: Any = ...) -> None: ...
def sortDefaultMethod(args: Any = ...) -> Any: ...
def standardise_path(path: str) -> str: ...
def which_program(name: str) -> str: ...
def debugInEclipse() -> None: ...
def debugInVSC() -> None: ...
def stopDebugging() -> None: ...
def createRMSDisplay(args: Any = ...) -> None: ...
def dealWithReportImage(args: Any = ...) -> Any: ...
def getReportExtraCIFItems() -> Any: ...
def getReportImageData() -> Any: ...
def getReportImageSrc() -> str: ...
def getReportPhilItem(key: str) -> Any: ...
def getReportTitleSrc() -> str: ...

# Available program lists
available_refinement_programs: List[str]
available_solution_programs: List[str]
programSettings: Any
