from typing import Any

class OlexFunctions:
    # File/Path
    def File(self) -> str: ...
    def FileDrive(self) -> str: ...
    def FileExt(self) -> str: ...
    def FileFull(self) -> str: ...
    def FileName(self) -> str: ...
    def FilePath(self) -> str: ...
    def BaseDir(self) -> str: ...
    def DataDir(self) -> str: ...
    def StrDir(self) -> str: ...
    def HKLSrc(self) -> str: ...
    def ModelSrc(self) -> str: ...
    def IsFileType(self, filetype: str) -> bool: ...

    # Parameters
    def GetParam(self, name: str, default: Any = ...) -> Any: ...
    def GetParam_as_string(self, name: str) -> str: ...
    def SetParam(self, name: str, value: Any) -> None: ...
    def StoreParameter(self, name: str, value: Any) -> None: ...
    def GetStoredParameter(self, name: str) -> Any: ...
    def SetDataParamN(self, name: str, value: Any) -> None: ...

    # Variables
    def GetVar(self, name: str) -> Any: ...
    def SetVar(self, name: str, value: Any) -> None: ...
    def IsVar(self, name: str) -> bool: ...
    def DelVar(self, name: str) -> None: ...

    # Refinement model
    def GetRefinementModel(self, include_connectivity: bool = ...) -> dict: ...
    def GetFVar(self, i: int) -> float: ...
    def SetFVar(self, i: int, value: float) -> None: ...
    def GetOSF(self) -> float: ...
    def SetOSF(self, value: float) -> None: ...
    def SetExtinction(self, value: float) -> None: ...
    def SetMaxCycles(self, n: int) -> None: ...
    def SetMaxPeaks(self, n: int) -> None: ...
    def SetSWAT(self, args: str = ...) -> None: ...

    # Structure info
    def GetFormula(self) -> str: ...
    def GetFormulaDisplay(self) -> str: ...
    def GetCellVolume(self) -> float: ...
    def GetCrystalData(self) -> dict: ...
    def IsAcentric(self) -> bool: ...
    def IsChiral(self) -> bool: ...
    def XfAuGetValue(self, args: str) -> Any: ...

    # Selection
    def GetCurrentSelection(self) -> str: ...

    # GUI
    def HasGUI(self) -> bool: ...
    def Refresh(self) -> None: ...
    def UpdateHtml(self) -> None: ...
    def Alert(self, title: str, message: str, buttons: str = ...) -> str: ...
    def Cursor(self, style: str = ...) -> None: ...
    def GetUserInput(self, args: str = ...) -> str: ...
    def SetFocus(self, control: str) -> None: ...
    def ShowModal(self, args: str = ...) -> None: ...
    def EndModal(self, args: str = ...) -> None: ...
    def IsPopup(self, name: str) -> bool: ...
    def HtmlLoad(self, args: str = ...) -> None: ...
    def HtmlDefineControl(self, args: str = ...) -> None: ...
    def SetHtmlFontSize(self, size: int) -> None: ...
    def SetHtmlFontSizeControls(self, size: int) -> None: ...
    def SetImage(self, args: str = ...) -> None: ...
    def SetGrad(self, args: str = ...) -> None: ...
    def SetPopBorder(self, args: str = ...) -> None: ...
    def MakeActiveGuiButton(self) -> None: ...
    def makeGeneralHtmlPop(self, args: str = ...) -> None: ...
    def htmlPanelWidth(self) -> int: ...
    def GetHtmlPanelX(self) -> int: ...
    def GetHtmlPanelwidth(self) -> int: ...

    # Controls
    def GetControlValue(self, control: str) -> str: ...
    def SetControlValue(self, control: str, value: str) -> None: ...
    def GetControlData(self, control: str) -> Any: ...
    def SetControlData(self, control: str, data: Any) -> None: ...
    def GetControlState(self, control: str) -> Any: ...
    def SetControlState(self, control: str, state: Any) -> None: ...
    def SetControlBG(self, control: str, color: str) -> None: ...
    def SetControlFG(self, control: str, color: str) -> None: ...
    def SetControlLabel(self, control: str, label: str) -> None: ...
    def SetControlItems(self, control: str, items: str) -> None: ...
    def SetControlEnabled(self, control: str, enabled: bool) -> None: ...
    def IsControlEnabled(self, control: str) -> bool: ...
    def IsControl(self, control: str) -> bool: ...
    def IsHtmlItem(self, item: str) -> bool: ...
    def GetItemState(self, item: str) -> Any: ...
    def SetItemState(self, item: str, state: Any) -> None: ...
    def SetControl(self, args: str = ...) -> None: ...
    def FindObject(self, name: str) -> Any: ...
    def FindValue(self, name: str) -> Any: ...

    # Registration
    def registerFunction(self, fn: object, profiling: bool, namespace: str) -> None: ...
    def registerMacro(self, fn: object, options: str, profiling: bool) -> None: ...
    def registerCallback(self, event: str, fn: object) -> None: ...
    def unregisterFunction(self, fn: object) -> None: ...
    def unregisterMacro(self, fn: object) -> None: ...
    def unregisterCallback(self, event: str, fn: object) -> None: ...

    # Commands
    def cmd(self, command: str) -> None: ...
    def runCommands(self, commands: list) -> None: ...
    def olex_function(self, fn: str) -> Any: ...
    def evaluate_function(self, fn: str) -> Any: ...
    def write_to_olex(self, text: str) -> None: ...

    # Utility
    def Lst(self, args: str = ...) -> str: ...
    def ListFiles(self, path: str = ...) -> list: ...
    def ListParts(self) -> list: ...
    def GetChoices(self, args: str = ...) -> list: ...
    def GetCifMergeFilesList(self) -> list: ...
    def GetACI(self) -> Any: ...
    def GetBaseTag(self) -> str: ...
    def GetTag(self) -> str: ...
    def GetDampingParams(self) -> Any: ...
    def GetHeaderParam(self, name: str) -> Any: ...
    def GetHeaderParamBool(self, name: str) -> bool: ...
    def SetHeaderParam(self, name: str, value: Any) -> None: ...
    def GetCompilationInfo(self) -> str: ...
    def GetComputername(self) -> str: ...
    def GetUsername(self) -> str: ...
    def GetUserComputerName(self) -> str: ...
    def GetMacAddress(self) -> str: ...
    def GetThreadN(self) -> int: ...
    def GetSVNVersion(self) -> str: ...
    def GetProgramVersionByName(self, name: str) -> str: ...
    def IsDebugging(self) -> bool: ...
    def IsDeveloping(self) -> bool: ...
    def IsDynamic(self) -> bool: ...
    def IsClientMode(self) -> bool: ...
    def IsRemoteMode(self) -> bool: ...
    def IsEDData(self) -> bool: ...
    def IsEDRefinement(self) -> bool: ...
    def IsNoSpherA2(self) -> bool: ...
    def IsPluginInstalled(self, name: str) -> bool: ...
    def HasCif(self) -> bool: ...
    def canNetwork(self) -> bool: ...
    def Reap(self, path: str) -> None: ...
    def AtReap(self) -> None: ...
    def Reset(self) -> None: ...
    def CifMerge(self, args: str = ...) -> None: ...
    def AddIns(self, ins: str) -> None: ...
    def DelIns(self, ins: str) -> None: ...
    def CopyVFSFile(self, args: str = ...) -> None: ...
    def CreateBitmap(self, args: str = ...) -> None: ...
    def DeleteBitmap(self, args: str = ...) -> None: ...
    def Listen(self, args: str = ...) -> None: ...
    def Params(self) -> Any: ...
    def GuiParams(self) -> Any: ...
    def Translate(self, text: str) -> str: ...
    def TranslatePhrase(self, phrase: str) -> str: ...
    def CurrentLanguageEncoding(self) -> str: ...
    def standardizePath(self, path: str) -> str: ...
    def standardizeListOfPaths(self, paths: list) -> list: ...
    def file_ChangeExt(self, path: str, ext: str) -> str: ...
    def get_cif_item(self, key: str) -> Any: ...
    def set_cif_item(self, key: str, value: Any) -> None: ...
    def get_txt_from_vfs(self, path: str) -> str: ...
    def reset_file_in_OFS(self, path: str) -> None: ...
    def external_edit(self, path: str) -> None: ...
    def getPYLPath(self) -> str: ...
    def get_diag(self) -> Any: ...
    def init_fast_linalg(self) -> None: ...
    def isInterruptSet(self) -> bool: ...
    def createFileLock(self, path: str) -> None: ...
    def deleteFileLock(self, path: str) -> None: ...
    def update_HklSrc(self, args: str = ...) -> None: ...
    def update_crystal_size(self, args: str = ...) -> None: ...
    def writeShelxFinFile(self, args: str = ...) -> None: ...
    def describe_refinement(self) -> str: ...
    def have_linked_occu(self) -> bool: ...
    def have_nsff(self) -> bool: ...
    def set_bond_thicknes(self, thickness: float) -> None: ...
    def setDisplayQuality(self, quality: str) -> None: ...
    def setAllMainToolbarTabButtons(self, args: str = ...) -> None: ...
    def set_refinement_program(self, program: str, method: str = ...) -> None: ...
    def set_solution_program(self, program: str, method: str = ...) -> None: ...
    def getCompatibleProgramName(self, name: str) -> str: ...
    def PrintMaskHKLWarning(self) -> None: ...
    def ResetMaskHKLWarning(self) -> None: ...
    def reloadStructureAtreap(self) -> None: ...
    def dict_obj(self, d: dict) -> Any: ...
    def GetValue(self, args: Any = ...) -> Any: ...
    def get_bool_from_any(self, value: Any) -> bool: ...
    def get_refienment_program_refrerence(self) -> str: ...
    def correct_rendered_text(self, text: str) -> str: ...
    def func_wrap(self, fn: object) -> object: ...
    def timer_wrap(self, fn: object) -> object: ...
    def _replace_object(self, args: Any = ...) -> Any: ...
    paramStack: Any
