from typing import Any

# --- xf namespace ---
class xf:
    @staticmethod
    def CurrentData() -> Any: ...
    @staticmethod
    def DataCount() -> int: ...
    @staticmethod
    def DataName() -> str: ...
    @staticmethod
    def EndUpdate() -> None: ...
    @staticmethod
    def GetDensity() -> float: ...
    @staticmethod
    def GetF000() -> float: ...
    @staticmethod
    def GetFormula(fmt: str = ...) -> str: ...
    @staticmethod
    def GetIncludedFiles() -> list: ...
    @staticmethod
    def GetMass() -> float: ...
    @staticmethod
    def GetMu() -> float: ...
    @staticmethod
    def RefinementInfo() -> dict: ...
    @staticmethod
    def SaveSolution(path: str = ...) -> None: ...
    @staticmethod
    def SetFormula(formula: str) -> None: ...

    class au:
        @staticmethod
        def Fractionalise(coords: Any) -> Any: ...
        @staticmethod
        def GetAUVolume() -> float: ...
        @staticmethod
        def GetAtomAfix(index: int) -> int: ...
        @staticmethod
        def GetAtomCount() -> int: ...
        @staticmethod
        def GetAtomCrd(index: int) -> tuple: ...
        @staticmethod
        def GetAtomName(index: int) -> str: ...
        @staticmethod
        def GetAtomOccu(index: int) -> float: ...
        @staticmethod
        def GetAtomPart(index: int) -> int: ...
        @staticmethod
        def GetAtomType(index: int) -> str: ...
        @staticmethod
        def GetAtomU(index: int) -> Any: ...
        @staticmethod
        def GetAtomUiso(index: int) -> float: ...
        @staticmethod
        def GetAtomlabel(index: int) -> str: ...
        @staticmethod
        def GetCell() -> tuple: ...
        @staticmethod
        def GetCellSymm() -> str: ...
        @staticmethod
        def GetCellVolume() -> float: ...
        @staticmethod
        def GetFormula() -> str: ...
        @staticmethod
        def GetPeak(index: int) -> float: ...
        @staticmethod
        def GetWeight() -> float: ...
        @staticmethod
        def GetZ() -> float: ...
        @staticmethod
        def GetZprime() -> float: ...
        @staticmethod
        def IsAtomDeleted(index: int) -> bool: ...
        @staticmethod
        def IsPeak(index: int) -> bool: ...
        @staticmethod
        def NPDCount() -> int: ...
        @staticmethod
        def NewAtom(args: Any = ...) -> Any: ...
        @staticmethod
        def Orthogonalise(coords: Any) -> Any: ...
        @staticmethod
        def SetAtomCrd(index: int, coords: Any) -> None: ...
        @staticmethod
        def SetAtomDisp(index: int, disp: Any) -> None: ...
        @staticmethod
        def SetAtomOccu(index: int, occu: float) -> None: ...
        @staticmethod
        def SetAtomPart(index: int, part: int) -> None: ...
        @staticmethod
        def SetAtomU(index: int, u: Any) -> None: ...
        @staticmethod
        def SetAtomlabel(index: int, label: str) -> None: ...
        @staticmethod
        def SetZ(z: float) -> None: ...
        @staticmethod
        def SetZprime(zprime: float) -> None: ...

    class rm:
        @staticmethod
        def BASF() -> float: ...
        @staticmethod
        def ClearParams() -> None: ...
        @staticmethod
        def Completeness() -> float: ...
        @staticmethod
        def Exti() -> float: ...
        @staticmethod
        def FVar(i: int) -> float: ...
        @staticmethod
        def HasOccu() -> bool: ...
        @staticmethod
        def MaxIndex() -> int: ...
        @staticmethod
        def ModelSrc() -> str: ...
        @staticmethod
        def NewAfixGroup(args: Any = ...) -> Any: ...
        @staticmethod
        def NewRestraint(args: Any = ...) -> Any: ...
        @staticmethod
        def OSF() -> float: ...
        @staticmethod
        def SWAT() -> Any: ...
        @staticmethod
        def ShareADP(args: Any = ...) -> None: ...
        @staticmethod
        def ShareDisp(args: Any = ...) -> None: ...
        @staticmethod
        def StoreParam(name: str, value: Any) -> None: ...
        @staticmethod
        def UpdateCR() -> None: ...

    class uc:
        @staticmethod
        def CellEx() -> tuple: ...
        @staticmethod
        def Closest(args: Any = ...) -> Any: ...
        @staticmethod
        def MatrixCount() -> int: ...
        @staticmethod
        def Volume() -> float: ...
        @staticmethod
        def VolumeEx() -> float: ...

    class latt:
        @staticmethod
        def GetFragmentAtoms(index: int) -> list: ...
        @staticmethod
        def GetFragmentCount() -> int: ...
        @staticmethod
        def GetMoiety() -> str: ...
        @staticmethod
        def IsGrown() -> bool: ...
        @staticmethod
        def IsPolymeric() -> bool: ...

    class exptl:
        @staticmethod
        def Radiation() -> float: ...
        @staticmethod
        def Size() -> tuple: ...
        @staticmethod
        def Temperature() -> float: ...

    class analysis:
        @staticmethod
        def AnalyseUeq(args: Any = ...) -> Any: ...
        @staticmethod
        def Scale() -> float: ...
        @staticmethod
        def Trim(args: Any = ...) -> Any: ...

# --- File / Path ---
def File() -> str: ...
def FileDrive() -> str: ...
def FileExt() -> str: ...
def FileFull() -> str: ...
def FileLast() -> str: ...
def FileName() -> str: ...
def FilePath() -> str: ...
def BaseDir() -> str: ...
def DataDir() -> str: ...
def StrDir() -> str: ...
def IsFileLoaded() -> bool: ...
def IsFileType(filetype: str) -> bool: ...
def FileOpen(path: str) -> None: ...
def FileSave(path: str) -> None: ...
def HKLSrc() -> str: ...

# --- Selection ---
def Sel(args: str = ...) -> str: ...
def SelBack() -> None: ...
def SelName() -> str: ...
def Info(args: str = ...) -> str: ...

# --- Atom/Structure manipulation ---
def Kill(atoms: str = ...) -> None: ...
def Move(args: str = ...) -> None: ...
def Name(args: str = ...) -> None: ...
def Split(args: str = ...) -> None: ...
def Fix(args: str = ...) -> None: ...
def Free(args: str = ...) -> None: ...
def Afix(args: str = ...) -> None: ...
def Isot(atoms: str = ...) -> None: ...
def Anis(atoms: str = ...) -> None: ...
def HAdd(atoms: str = ...) -> None: ...
def HAddCount() -> int: ...
def Part(args: str = ...) -> None: ...
def RESI(args: str = ...) -> None: ...
def Sort(args: str = ...) -> None: ...
def Uniq(args: str = ...) -> None: ...
def Compaq(args: str = ...) -> None: ...
def Fuse() -> None: ...
def Grow(args: str = ...) -> None: ...
def Pack(args: str = ...) -> None: ...
def Cent() -> None: ...
def Inv(args: str = ...) -> None: ...
def Individualise(args: str = ...) -> None: ...
def Collectivise(args: str = ...) -> None: ...
def EditAtom(args: str = ...) -> None: ...

# --- Bonds ---
def AddBond(args: str = ...) -> None: ...
def DelBond(args: str = ...) -> None: ...
def FBond(args: str = ...) -> None: ...
def Conn(args: str = ...) -> None: ...

# --- Geometry ---
def Angle(args: str = ...) -> str: ...
def Envi(args: str = ...) -> str: ...
def Esd(args: str = ...) -> str: ...
def Mpln(args: str = ...) -> str: ...
def Lpln(args: str = ...) -> str: ...
def Htab(args: str = ...) -> None: ...
def PiPi(args: str = ...) -> None: ...
def Tria(args: str = ...) -> None: ...

# --- Restraints/Constraints ---
def Dfix(args: str = ...) -> None: ...
def Dang(args: str = ...) -> None: ...
def Sadi(args: str = ...) -> None: ...
def Same(args: str = ...) -> None: ...
def Flat(args: str = ...) -> None: ...
def Chiv(args: str = ...) -> None: ...
def SIMU(args: str = ...) -> None: ...
def DELU(args: str = ...) -> None: ...
def RIGU(args: str = ...) -> None: ...
def ISOR(args: str = ...) -> None: ...
def EADP(args: str = ...) -> None: ...
def EXYZ(args: str = ...) -> None: ...
def Sump(args: str = ...) -> None: ...
def Fvar(args: str = ...) -> None: ...
def Link(args: str = ...) -> None: ...
def Restrain(args: str = ...) -> None: ...
def Constrain(args: str = ...) -> None: ...

# --- Refinement ---
def Refine(args: str = ...) -> None: ...
def CalcR(args: str = ...) -> str: ...
def CalcVars() -> None: ...
def LS(args: str = ...) -> None: ...
def LSM(args: str = ...) -> None: ...
def Plan(n: int = ...) -> None: ...
def Reset(args: str = ...) -> None: ...
def OnRefine() -> None: ...
def UpdateWght(args: str = ...) -> None: ...
def UpdateAfix(args: str = ...) -> None: ...

# --- Display ---
def Freeze(state: bool) -> None: ...
def Labels(args: str = ...) -> None: ...
def Label(args: str = ...) -> None: ...
def ShowH(state: bool = ...) -> None: ...
def ShowQ(state: bool = ...) -> None: ...
def ShowR(args: str = ...) -> None: ...
def Hide(args: str = ...) -> None: ...
def Visible(args: str = ...) -> None: ...
def Center() -> None: ...
def SetView(args: str = ...) -> None: ...
def Zoom(args: str = ...) -> None: ...
def AZoom(args: str = ...) -> None: ...
def ARad(args: str = ...) -> None: ...
def BRad(args: str = ...) -> None: ...
def TelpV(args: str = ...) -> None: ...
def Qual(args: str = ...) -> None: ...
def Style(args: str = ...) -> None: ...
def Color(args: str = ...) -> None: ...
def Poly(args: str = ...) -> None: ...
def Basis(args: str = ...) -> None: ...
def Legend(args: str = ...) -> None: ...
def Pict(args: str = ...) -> None: ...

# --- CIF ---
def Cif(args: str = ...) -> None: ...
def CifCreate(args: str = ...) -> None: ...
def CifMerge(args: str = ...) -> None: ...
def CifExtract(args: str = ...) -> None: ...

# --- Variables ---
def GetVar(name: str) -> Any: ...
def SetVar(name: str, value: Any) -> None: ...
def IsVar(name: str) -> bool: ...
def UnsetVar(name: str) -> None: ...
def DefineVar(name: str, value: Any = ...) -> None: ...
def LstVar() -> None: ...

# --- Utility ---
def Echo(message: str = ...) -> None: ...
def Refresh() -> None: ...
def Reload() -> None: ...
def Restart() -> None: ...
def Exit() -> None: ...
def HasGUI() -> bool: ...
def IsOS(os: str) -> bool: ...
def Run(args: str = ...) -> None: ...
def Exec(args: str = ...) -> None: ...
def Shell(args: str = ...) -> None: ...
def Wait(ms: int = ...) -> None: ...
def Update(args: str = ...) -> None: ...
def Help(command: str = ...) -> None: ...
def TranslatePhrase(phrase: str) -> str: ...
def CurrentLanguage() -> str: ...
def CurrentLanguageEncoding() -> str: ...
def IsCurrentLanguage(lang: str) -> bool: ...
def GetUserInput(args: str = ...) -> str: ...
def GetUserStyledInput(args: str = ...) -> str: ...
def Alert(title: str, message: str, buttons: str = ...) -> str: ...
def Cursor(style: str = ...) -> None: ...
def SG(args: str = ...) -> str: ...
def SGInfo(args: str = ...) -> str: ...
def SGList(args: str = ...) -> str: ...
def LstSymm() -> None: ...
def LstIns() -> None: ...
def LstFun() -> None: ...
def LstMac() -> None: ...
def Cell() -> str: ...
def CalcMass() -> str: ...
def CalcVol() -> str: ...
def CalcSurf() -> str: ...
def CalcVoid() -> str: ...
def MolInfo() -> str: ...
def AtomInfo(args: str = ...) -> str: ...
def Atoms(args: str = ...) -> str: ...
def Ins(args: str = ...) -> str: ...
def AddIns(ins: str) -> None: ...
def DelIns(ins: str) -> None: ...
def Title(title: str = ...) -> str: ...
def Undo() -> None: ...
def Listen(args: str = ...) -> None: ...
def Match(args: str = ...) -> None: ...
def Mode(args: str = ...) -> None: ...
def Process(args: str = ...) -> None: ...

# --- Submodules exposed as attributes ---
xf: xf
olex: Any
gl: Any
html: Any
gui_phil_handler: Any
phil_handler: Any
math: Any
sys: Any
time: Any
